### ISSUE TITLE
[세팅] Mysql DB 생성/연동 및 일부 컬럼(필드) 수정

### ISSUE THREAD

**Issue by hjjae2** [pigs-pango-team/gg-pigs-api#16]
**[세팅] Mysql DB 연동 및 일부 컬럼(필드) 수정**

1. Mysql DB 생성/연동: pango_db
`application.yml`
```
spring:
  datasource:
    url: jdbc:mysql://[호스트]:[포트]/[DB명]?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: [아이디]
    password: [패스워드]
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      ...
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

...
```

> 포트 설정 & 로깅 (임시) : java -Dserver.port=[포트번호] -jar [jar파일] >> [로그파일] &
> 포트포워딩 & 방화벽(ufw) 설정 필요

2. 일부 컬럼(필드) 수정: Long -> String, Boolean -> Char
- **Advertisement, AdvertisementRequest**: rowPosition, columnPosition, isActivated
- **AdvertisementType**: width, height
